version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/scrum-dice
    overwrite: yes
permissions:
  - object: /home/ec2-user/scrum-dice
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/scrum-dice
    owner: ec2-user
    group: ec2-user
    mode: 664
    type:
      - file
hooks:
  AfterInstall:
    - location: codedeploy/docker-build-run.sh
      runas: root
