import Head from 'next/head';

// styles
import classNames from 'classnames';
import { Noto_Sans_KR, Lato } from 'next/font/google';

// Todo: atomic 디자인 패턴 실험중에만 하기의 컴포넌트를 추가한다.
import Button from '@/components/atoms/button/Button';
import { Card } from '@/components/atoms/card';

const notoSansKr = Noto_Sans_KR({
  // preload: true, 기본값
  subsets: ['latin'], // 또는 preload: false
  weight: ['100', '400', '700', '900'], // 가변 폰트가 아닌 경우, 사용할 fontWeight 배열
});

const lato = Lato({
  subsets: ['latin'], // preload에 사용할 subsets입니다.
  weight: ['100', '400', '700', '900'],
  variable: '--lato', // CSS 변수 방식으로 스타일을 지정할 경우에 사용합니다.
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classNames(notoSansKr.className, lato.variable)}>
        <div className="mockup-window border bg-base-300 m-8">
          <div className="flex space-x-2 justify-center px-4 py-16 bg-base-200">
            <Card state="openedMe">0</Card>
            <Card state="selectable">1</Card>
            <Card state="selected">2</Card>
            <Card state="selectable">3</Card>
            <Card state="selectable">5</Card>
            <Card state="selectable">8</Card>
            <Card state="selectable">13</Card>
            <Card state="selectable">21</Card>
            <Card state="openedOther">23</Card>
            <Card state="openedOther">25</Card>
          </div>
        </div>
      </main>
    </>
  );
}
