import { Paragraph } from '@/components/atoms/Paragraph';
import Head from 'next/head';
import Link from 'next/link';

import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

export default function Home() {
  const translate = useTranslation(['common', 'createroom']).t;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-4">
        <Paragraph size="large">
          <Link href="/login">{ translate('common:게스트로_로그인하기') }</Link>
        </Paragraph>
        <Paragraph size="large">
          <Link href="/room">{ translate('common:플래닝_포커_방_생성하기') }</Link>
        </Paragraph>
      </main>
    </>
  );
}

export const getStaticProps = async ({ locale }: any) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common', 'createroom'])),
  },
});
